service: w2-document-api

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline

functions:
  authorizer:
    name: test-authorizer
    handler: index.handler
    events:
      - http:
          path: '{proxy+}'
          method: ANY
